"""Telling Omnia's own output apart from the user's, so a regeneration knows what it may destroy.

The predicate that matters is not "did Omnia write this" but "did Omnia write this, and is it
still exactly what Omnia wrote". A mark that only says "mine" survives the user's edits and then
authorises throwing them away — the one outcome the setting exists to prevent.
"""

from __future__ import annotations

import pytest

from omnia.plugins.smart_notes.provenance import (
    ALWAYS,
    NOT_OURS,
    OURS_ONLY,
    SCOPES,
    is_marked,
    is_ours,
    is_untouched,
    may_overwrite,
    our_media_refs,
    stamp,
    to_store,
    unstamp,
)


class TestTheMarkOnText:
    def test_a_stamped_value_reads_back_unchanged(self):
        # The mark is invisible while reviewing; a reader must see exactly what was generated.
        assert unstamp(stamp("<b>a definition</b>")) == "<b>a definition</b>"

    def test_stamping_twice_does_not_stack_marks(self):
        # Regeneration writes over a field that already carries one.
        once = stamp("hello")

        assert stamp(once) == once

    def test_it_recognises_its_own(self):
        assert is_untouched(stamp("hello")) is True

    def test_an_edit_breaks_the_match(self):
        """The whole point.

        An HTML comment is a DOM node: typing beside it leaves it in place. Verified in
        Chromium — a contenteditable round trip keeps the comment and an edit changes the text
        next to it, so the fingerprint stops matching and the field is correctly read as the
        user's.
        """
        edited = stamp("hello").replace("hello", "hello, edited")

        assert (
            is_marked(edited) is True
        ), "the mark survived the edit, as it does in Anki"
        assert (
            is_untouched(edited) is False
        ), "so the FINGERPRINT has to be what decides"

    def test_something_nobody_marked_is_not_ours(self):
        assert is_untouched("<b>hand written</b>") is False
        assert is_marked("<b>hand written</b>") is False

    def test_a_forged_looking_mark_with_the_wrong_digest_is_not_ours(self):
        assert is_untouched("<!--omnia:000000-->hello") is False

    def test_an_empty_field_is_nobody_s(self):
        assert is_ours("") is False
        assert is_ours("   ") is False


class TestMediaNeedsNoMark:
    """A sound field is one tag whose NAME already says who wrote it."""

    def test_our_audio_is_ours(self):
        assert is_ours("[sound:omnia-1-Audio.mp3]") is True

    def test_our_image_is_ours(self):
        assert is_ours('<img src="omnia-1-Pic.png">') is True

    def test_another_addons_audio_is_not(self):
        # AwesomeTTS and HyperTTS write `googletts-…`; pasted images land as `paste-…`.
        assert is_ours("[sound:googletts-b4728f64.mp3]") is False
        assert is_ours('<img src="paste-abc.jpg">') is False

    def test_a_field_mixing_both_is_not_ours(self):
        # Half somebody else's is not ours to replace.
        assert is_ours('[sound:omnia-1-A.mp3] <img src="paste-abc.jpg">') is False

    def test_reading_back_only_our_files(self):
        both = '[sound:googletts-aaa.mp3] <img src="omnia-9-Pic.png">'

        assert our_media_refs(both) == ["omnia-9-Pic.png"]

    def test_the_same_file_twice_is_listed_once(self):
        assert our_media_refs("[sound:omnia-1-A.mp3] [sound:omnia-1-A.mp3]") == [
            "omnia-1-A.mp3"
        ]


class TestWhatAScopeAllows:
    OURS = stamp("generated by omnia")
    THEIRS = "<b>written by hand</b>"
    OUR_AUDIO = "[sound:omnia-1-A.mp3]"

    def test_an_empty_field_is_writable_under_every_scope(self):
        # A setting about OVERWRITING has no business stopping a field being filled at all.
        for scope in SCOPES:
            assert may_overwrite("", scope) is True, scope

    def test_always_replaces_anything(self):
        assert may_overwrite(self.THEIRS, ALWAYS) is True
        assert may_overwrite(self.OURS, ALWAYS) is True

    def test_ours_only_protects_what_the_user_wrote(self):
        assert may_overwrite(self.OURS, OURS_ONLY) is True
        assert may_overwrite(self.OUR_AUDIO, OURS_ONLY) is True
        assert may_overwrite(self.THEIRS, OURS_ONLY) is False

    def test_ours_only_stops_protecting_once_the_user_edits_it(self):
        edited = self.OURS.replace("generated", "generated and then improved")

        assert may_overwrite(edited, OURS_ONLY) is False

    def test_not_ours_protects_what_omnia_already_paid_for(self):
        # Audio already generated cost real provider money; regenerating buys it twice.
        assert may_overwrite(self.OUR_AUDIO, NOT_OURS) is False
        assert may_overwrite(self.OURS, NOT_OURS) is False
        assert may_overwrite(self.THEIRS, NOT_OURS) is True

    @pytest.mark.parametrize("scope", ["", "something_a_newer_omnia_added", None])
    def test_an_unrecognised_scope_behaves_as_it_did_before_the_setting_existed(
        self, scope
    ):
        """A config from a newer Omnia must not quietly stop generating.

        ADR-010's hazard in miniature: the value is kept and not understood, and the safe
        reading of "I do not know this" is the behaviour that shipped before the key existed.
        """
        assert may_overwrite(self.THEIRS, scope) is True


class TestAnUnknownScopeLoadsRatherThanRaising:
    """`overwrite_scope` is a plain `str` on purpose, and ADR-010 is the whole reason.

    `SmartNotesStore.load` calls `parse_obj` with no try/except, from inside the note-add and
    review hooks. A `Literal` turns a value this build does not know into a hard
    ValidationError on every load: the settings dialog will not open and smart-notes dies
    mid-review. Not hypothetical — an intermediate commit on this branch shipped a fourth
    scope, `never`, so a profile that ran it has `never` in its synced blob.
    """

    def _settings(self, value):
        from omnia.plugins.smart_notes.config import SmartNotesSettings

        return SmartNotesSettings.parse_obj({"overwrite_scope": value})

    def test_a_scope_this_build_removed_still_loads(self):
        assert self._settings("never").overwrite_scope == "never"

    def test_a_scope_a_future_release_adds_still_loads(self):
        assert (
            self._settings("whatever_comes_next").overwrite_scope
            == "whatever_comes_next"
        )

    def test_the_value_round_trips_verbatim(self):
        """Kept, not normalised: the blob syncs, so rewriting it here would send the damage
        back to the newer device that wrote it."""
        assert self._settings("never").dict()["overwrite_scope"] == "never"

    def test_an_unknown_scope_behaves_as_always(self):
        # `may_overwrite`'s documented fallback, which a Literal made unreachable.
        assert may_overwrite("hand-written", "never") is True
        assert may_overwrite("hand-written", "whatever_comes_next") is True


class TestUserTextBesideOurAudioIsNotOurs:
    """ "Nothing to edit inside a sound reference" is true of the reference, not of the field."""

    def test_our_tag_alone_is_ours(self):
        assert is_ours("[sound:omnia-1-A.mp3]") is True

    def test_our_tag_with_whitespace_is_still_ours(self):
        assert is_ours("  [sound:omnia-1-A.mp3]\n") is True

    def test_a_note_typed_beside_our_tag_is_not(self):
        """Under `ours_only` this field would be overwritten and the user's note destroyed —
        by the one setting they chose to prevent exactly that."""
        assert is_ours("[sound:omnia-1-A.mp3] (stress on the second syllable)") is False

    def test_our_image_with_a_caption_is_not(self):
        assert is_ours('<img src="omnia-1-Pic.png"> a rusted bridge') is False

    def test_two_of_our_tags_are_still_ours(self):
        assert is_ours("[sound:omnia-1-A.mp3][sound:omnia-1-B.mp3]") is True


class TestTheMarkDoesNotReachTheNextRunsPrompt:
    """Stamping at the write keeps the comment out of a CHAINED tool's prompt within one run.

    It says nothing about the next run, which loads the stamped value back off the note — and
    the callers read note fields raw because the skip logic needs the mark to answer whose work
    a field is. So the strip happens at interpolation, the one boundary where a stored value
    becomes something a model reads.
    """

    def test_a_stamped_source_field_is_substituted_clean(self):
        from omnia.plugins.smart_notes.engine.interpolation import interpolate

        out = interpolate("define {{Word}}", {"Word": stamp("cat")})

        assert out == "define cat"
        assert "omnia:" not in out

    def test_an_unstamped_field_is_untouched(self):
        from omnia.plugins.smart_notes.engine.interpolation import interpolate

        assert interpolate("define {{Word}}", {"Word": "cat"}) == "define cat"

    def test_the_split_prompt_stays_lossless(self):
        # `split_prompt` promises prefix + suffix is byte-for-byte `interpolate`'s answer.
        from omnia.plugins.smart_notes.engine.interpolation import (
            interpolate,
            split_prompt,
        )

        fields = {"Word": stamp("cat")}
        parts = split_prompt("define {{Word}} well", fields)

        assert parts.prefix + parts.suffix == interpolate(
            "define {{Word}} well", fields
        )


class TestEveryPathThatWritesGeneratedTextMarksIt:
    """Four paths write generated content into a note, and the mark is worth nothing unless
    all four apply it.

    Stamping lived in the batch runner alone, so the editor's Generate button, review-time
    pre-generation and the clipper's regeneration wrote Omnia's text unmarked. Under
    ``ours_only`` those fields then read as somebody else's work and were never refreshed;
    under ``not_ours`` they were regenerated on every batch and paid for again. Both silent.

    Audio and images escape via the ``omnia-`` filename prefix — text is the case the mark
    exists for, and text is what these four write.

    A source-reading test, because the alternative is four integration harnesses to pin one
    property, and the property is "this call goes through `to_store`". A path that stops doing
    so fails here with the name of the file that dropped it.
    """

    #: Every module that turns a generation result into a value stored on a note.
    WRITE_PATHS = (
        ("the batch runner", "src/omnia/plugins/smart_notes/integration/batch.py"),
        ("the editor Generate button", "src/omnia/plugins/smart_notes/__init__.py"),
        (
            "review-time pre-generation",
            "src/omnia/plugins/smart_notes/integration/review.py",
        ),
        (
            "the clipper regeneration",
            "src/omnia/plugins/smart_notes/integration/regen.py",
        ),
        # The custom-prompt dialog, not the `on_save` callback that stores what it hands over:
        # the kind is only in hand on this side, and marking here covers every caller of the
        # dialog rather than just the one that exists today.
        (
            "the editor custom-prompt action",
            "src/omnia/gui/smart_notes/dialogs/prompt.py",
        ),
    )

    def _source(self, path: str) -> str:
        import pathlib

        root = pathlib.Path(__file__).resolve().parents[3]
        return (root / path).read_text(encoding="utf-8")

    @pytest.mark.parametrize("label,path", WRITE_PATHS)
    def test_it_goes_through_to_store(self, label, path):
        assert "to_store(" in self._source(
            path
        ), f"{label} writes generated content without marking it as Omnia's"

    def test_to_store_marks_text(self):
        assert is_untouched(to_store("a definition", "text"))

    @pytest.mark.parametrize("kind", ["tts", "image"])
    def test_to_store_leaves_media_alone(self, kind):
        # The filename already says who wrote it; a comment beside one tag is clutter.
        assert to_store("[sound:omnia-1-A.mp3]", kind) == "[sound:omnia-1-A.mp3]"

    def test_a_marked_value_reads_back_as_ours(self):
        # The round trip the whole feature rests on.
        assert is_ours(to_store("a definition", "text")) is True

    def test_materialize_does_not_stamp(self):
        """Stamping belongs on the WRITE, not in `materialize`: its value is what a chained
        tool reads next, and a mark there would be quoted into the following prompt."""
        source = self._source("src/omnia/plugins/smart_notes/integration/batch.py")
        body = source[source.index("def materialize(nid: int") :]
        body = body[: body.index("\ndef ", 1)] if "\ndef " in body[1:] else body

        assert "stamp(" not in body


class TestAnEmptyResultIsNotMarked:
    """A bare mark is not an empty field to anything that asks.

    ``to_store("", "text")`` would produce ``<!--omnia:da39a3-->``: ``should_skip_rule`` reads
    that as filled and skips the field, so a field that generated nothing would never be tried
    again — and ``is_untouched`` says it is ours, so ``not_ours`` would not retry it either.
    """

    def test_an_empty_value_stays_empty(self):
        assert to_store("", "text") == ""

    def test_whitespace_only_stays_as_it_was(self):
        assert to_store("   ", "text") == "   "

    def test_a_real_value_is_still_marked(self):
        assert is_untouched(to_store("a definition", "text"))
