"""Telling Omnia's own output apart from the user's, so a regeneration knows what it may destroy.

The predicate that matters is not "did Omnia write this" but "did Omnia write this, and is it
still exactly what Omnia wrote". A mark that only says "mine" survives the user's edits and then
authorises throwing them away — the one outcome the setting exists to prevent.
"""

from __future__ import annotations

import pytest

from omnia.plugins.smart_notes.provenance import (
    ALWAYS,
    NEVER,
    NOT_OURS,
    OURS_ONLY,
    SCOPES,
    is_marked,
    is_ours,
    is_untouched,
    may_overwrite,
    our_media_refs,
    stamp,
    unstamp,
)


class TestTheMarkOnText:
    def test_a_stamped_value_reads_back_unchanged(self):
        # The mark is invisible while reviewing; a reader must see exactly what was generated.
        assert unstamp(stamp("<b>a definition</b>")) == "<b>a definition</b>"

    def test_stamping_twice_does_not_stack_marks(self):
        # Regeneration writes over a field that already carries one.
        once = stamp("hello")

        assert stamp(once) == once

    def test_it_recognises_its_own(self):
        assert is_untouched(stamp("hello")) is True

    def test_an_edit_breaks_the_match(self):
        """The whole point.

        An HTML comment is a DOM node: typing beside it leaves it in place. Verified in
        Chromium — a contenteditable round trip keeps the comment and an edit changes the text
        next to it, so the fingerprint stops matching and the field is correctly read as the
        user's.
        """
        edited = stamp("hello").replace("hello", "hello, edited")

        assert (
            is_marked(edited) is True
        ), "the mark survived the edit, as it does in Anki"
        assert (
            is_untouched(edited) is False
        ), "so the FINGERPRINT has to be what decides"

    def test_something_nobody_marked_is_not_ours(self):
        assert is_untouched("<b>hand written</b>") is False
        assert is_marked("<b>hand written</b>") is False

    def test_a_forged_looking_mark_with_the_wrong_digest_is_not_ours(self):
        assert is_untouched("<!--omnia:000000-->hello") is False

    def test_an_empty_field_is_nobody_s(self):
        assert is_ours("") is False
        assert is_ours("   ") is False


class TestMediaNeedsNoMark:
    """A sound field is one tag whose NAME already says who wrote it."""

    def test_our_audio_is_ours(self):
        assert is_ours("[sound:omnia-1-Audio.mp3]") is True

    def test_our_image_is_ours(self):
        assert is_ours('<img src="omnia-1-Pic.png">') is True

    def test_another_addons_audio_is_not(self):
        # AwesomeTTS and HyperTTS write `googletts-…`; pasted images land as `paste-…`.
        assert is_ours("[sound:googletts-b4728f64.mp3]") is False
        assert is_ours('<img src="paste-abc.jpg">') is False

    def test_a_field_mixing_both_is_not_ours(self):
        # Half somebody else's is not ours to replace.
        assert is_ours('[sound:omnia-1-A.mp3] <img src="paste-abc.jpg">') is False

    def test_reading_back_only_our_files(self):
        both = '[sound:googletts-aaa.mp3] <img src="omnia-9-Pic.png">'

        assert our_media_refs(both) == ["omnia-9-Pic.png"]

    def test_the_same_file_twice_is_listed_once(self):
        assert our_media_refs("[sound:omnia-1-A.mp3] [sound:omnia-1-A.mp3]") == [
            "omnia-1-A.mp3"
        ]


class TestWhatAScopeAllows:
    OURS = stamp("generated by omnia")
    THEIRS = "<b>written by hand</b>"
    OUR_AUDIO = "[sound:omnia-1-A.mp3]"

    def test_an_empty_field_is_writable_under_every_scope(self):
        # A setting about OVERWRITING has no business stopping a field being filled at all.
        for scope in SCOPES:
            assert may_overwrite("", scope) is True, scope

    def test_always_replaces_anything(self):
        assert may_overwrite(self.THEIRS, ALWAYS) is True
        assert may_overwrite(self.OURS, ALWAYS) is True

    def test_never_replaces_nothing_that_has_content(self):
        assert may_overwrite(self.THEIRS, NEVER) is False
        assert may_overwrite(self.OURS, NEVER) is False

    def test_ours_only_protects_what_the_user_wrote(self):
        assert may_overwrite(self.OURS, OURS_ONLY) is True
        assert may_overwrite(self.OUR_AUDIO, OURS_ONLY) is True
        assert may_overwrite(self.THEIRS, OURS_ONLY) is False

    def test_ours_only_stops_protecting_once_the_user_edits_it(self):
        edited = self.OURS.replace("generated", "generated and then improved")

        assert may_overwrite(edited, OURS_ONLY) is False

    def test_not_ours_protects_what_omnia_already_paid_for(self):
        # Audio already generated cost real provider money; regenerating buys it twice.
        assert may_overwrite(self.OUR_AUDIO, NOT_OURS) is False
        assert may_overwrite(self.OURS, NOT_OURS) is False
        assert may_overwrite(self.THEIRS, NOT_OURS) is True

    @pytest.mark.parametrize("scope", ["", "something_a_newer_omnia_added", None])
    def test_an_unrecognised_scope_behaves_as_it_did_before_the_setting_existed(
        self, scope
    ):
        """A config from a newer Omnia must not quietly stop generating.

        ADR-010's hazard in miniature: the value is kept and not understood, and the safe
        reading of "I do not know this" is the behaviour that shipped before the key existed.
        """
        assert may_overwrite(self.THEIRS, scope) is True
