
  /**
   * Smart Notes config page — the per-row Tools picker (a MIDDLE fragment of the page IIFE; it
   * neither opens nor closes it). A field is generated by an ORDERED CHAIN of tools, tried
   * top-down until one produces a result, so a free deterministic tool (cloze) can run first and
   * only fall through to the paid `ai` tool when it declines. An EMPTY chain is the legacy
   * default and means exactly "generate with AI".
   *
   * The chain lives as JSON on the row's data-tools attribute — the same single-source-of-truth
   * trick as data-depends-on — so `collectRows` (03-render.js) posts it with every other row
   * value and the existing Save persists it. The catalog of installable tools is BAKED into
   * `window.__SN_TOOLS` server-side (like `__SN_CATALOG`), so the picker paints on first open
   * with no pycmd round-trip.
   *
   * `makeToolsCell` / `updateToolsSummary` / `readTools` / `writeTools` are hoisted function
   * declarations called from 03-render.js, which is concatenated BEFORE this file.
   */

  // [{name, label, description, kinds, deterministic, params_schema, unavailable_reason}, ...]
  const TOOLS = window.__SN_TOOLS || [];

  const toolsModal = document.getElementById("sn-tools-modal");
  const toolsTitle = document.getElementById("sn-tools-title");
  const toolsList = document.getElementById("sn-tools-list");
  const toolsEmpty = document.getElementById("sn-tools-empty");
  const toolsClose = document.getElementById("sn-tools-close");
  const toolsCancel = document.getElementById("sn-tools-cancel");
  const toolsDone = document.getElementById("sn-tools-done");

  // The row whose chain is open in the picker (null when closed) + the working copy being
  // edited. Cancel simply drops the copy, so the row is only ever touched by Done.
  let toolsRow = null;
  let toolsDraft = [];

  /**
   * The catalog entry for a tool name, or null when this build doesn't have it (a user tool
   * authored on another device — its name is still kept in the chain).
   * @param {string} name The tool name.
   * @return {?Object}
   */
  function toolSpec(name) {
    let found = null;
    TOOLS.forEach(function (spec) {
      if (spec.name === name) {
        found = spec;
      }
    });
    return found;
  }

  /**
   * Read a row's tool chain (JSON on its data-tools attribute).
   * @param {!HTMLElement} tr The row.
   * @return {!Array<!Object>} The chain entries ({tool, params}); [] if unset/invalid.
   */
  function readTools(tr) {
    try {
      const parsed = JSON.parse(tr.dataset.tools || "[]");
      return Array.isArray(parsed) ? parsed : [];
    } catch (e) {
      return [];
    }
  }

  /**
   * Write a row's tool chain back and refresh its summary button.
   * @param {!HTMLElement} tr The row.
   * @param {!Array<!Object>} chain The ordered entries ({tool, params}).
   */
  function writeTools(tr, chain) {
    tr.dataset.tools = JSON.stringify(chain || []);
    updateToolsSummary(tr);
  }

  /**
   * Build the Tools cell: a button whose label IS the chain ("cloze → AI"), opening the picker.
   * @param {!HTMLTableRowElement} tr The owning row.
   * @return {!HTMLTableCellElement}
   */
  function makeToolsCell(tr) {
    const td = cell("sn-tools-cell sn-lockable");
    const btn = document.createElement("button");
    btn.type = "button";
    btn.className = "sn-btn sn-tools-btn";
    btn.addEventListener("click", function () {
      if (!tr.classList.contains("sn-row-locked")) {
        openToolsPicker(tr);
      }
    });
    td.appendChild(btn);
    return td;
  }

  /**
   * Reflect the row's chain on its Tools button ("AI" when empty — that IS the default).
   * @param {!HTMLTableRowElement} tr The row to refresh.
   */
  function updateToolsSummary(tr) {
    const btn = tr.querySelector(".sn-tools-btn");
    if (!btn) {
      return;
    }
    const chain = readTools(tr);
    const labels = chain.map(function (entry) {
      const spec = toolSpec(entry.tool);
      return spec ? spec.label : entry.tool;
    });
    btn.textContent = labels.length ? labels.join(" → ") : "AI";
    btn.classList.toggle("sn-tools-default", !labels.length);
    btn.title = labels.length
      ? "Tried in order until one produces: " + labels.join(" → ")
      : "Generated by AI (the default) — click to add a deterministic tool first.";
  }

  /**
   * Open the picker for a row, on a COPY of its chain (Cancel must change nothing).
   * @param {!HTMLTableRowElement} tr The row whose chain is edited.
   */
  function openToolsPicker(tr) {
    toolsRow = tr;
    toolsDraft = readTools(tr)
      .filter(function (entry) {
        return entry && entry.tool;
      })
      .map(function (entry) {
        // Copy the params object rather than reference it: a param this build cannot render
        // (added by a newer release) must survive Done untouched.
        const params = {};
        Object.keys(entry.params || {}).forEach(function (key) {
          params[key] = entry.params[key];
        });
        return {tool: String(entry.tool), params: params};
      });
    toolsTitle.textContent = "Tools — " + tr.dataset.field;
    renderToolsPicker();
    toolsModal.hidden = false;
  }

  /** Close the picker without touching the row. */
  function closeToolsPicker() {
    toolsModal.hidden = true;
    toolsRow = null;
    toolsDraft = [];
  }

  /** The generation kind of the row being edited ("" when the picker is closed). */
  function toolsRowKind() {
    if (!toolsRow) {
      return "";
    }
    const sel = toolsRow.querySelector(".sn-type");
    return sel ? sel.value : "";
  }

  /**
   * Why a tool can't be used for this row, or "" when it can. Two very different reasons —
   * the tool doesn't serve this field's type, or the backend reported it unavailable (no
   * provider, no runtime) — read the same way in the list: greyed, with the reason spelled out.
   * @param {?Object} spec The catalog entry (null = not installed here).
   * @param {string} kind The row's generation kind.
   * @return {string}
   */
  function toolUnavailable(spec, kind) {
    if (!spec) {
      return "Not installed on this device — this field skips it and tries the next tool.";
    }
    if ((spec.kinds || []).indexOf(kind) < 0) {
      return "Can't generate a “" + (TYPE_LABELS[kind] || kind) + "” field.";
    }
    return spec.unavailable_reason || "";
  }

  /** Render the whole picker: the chain in order, then the tools that could still be added. */
  function renderToolsPicker() {
    const kind = toolsRowKind();
    toolsList.innerHTML = "";
    const inChain = {};
    toolsDraft.forEach(function (entry, index) {
      inChain[entry.tool] = true;
      toolsList.appendChild(toolEntryRow(entry, index, kind));
    });
    let offered = 0;
    TOOLS.forEach(function (spec) {
      if (inChain[spec.name] || (spec.kinds || []).indexOf(kind) < 0) {
        return;
      }
      offered += 1;
      toolsList.appendChild(toolEntryRow({tool: spec.name, params: {}}, -1, kind));
    });
    toolsEmpty.textContent =
      toolsDraft.length || offered
        ? ""
        : "No tool can generate this field type — it is generated by AI.";
  }

  /**
   * Build one tool's row: include checkbox, order controls, description, and its params form.
   * @param {!Object} entry The chain entry ({tool, params}).
   * @param {number} index Its position in the chain, or -1 when it isn't in it.
   * @param {string} kind The row's generation kind.
   * @return {!HTMLElement}
   */
  function toolEntryRow(entry, index, kind) {
    const spec = toolSpec(entry.tool);
    const reason = toolUnavailable(spec, kind);
    const row = document.createElement("div");
    row.className = "sn-tool-row" + (reason ? " sn-tool-unavailable" : "");

    const head = document.createElement("div");
    head.className = "sn-tool-head";

    const label = document.createElement("label");
    label.className = "sn-tool-label";
    const cb = makeCheckbox("sn-tool-include", index >= 0);
    // An unusable tool can't be ADDED, but one already configured stays removable — otherwise a
    // chain that became invalid (type changed on another device) could never be repaired here.
    cb.disabled = !!reason && index < 0;
    cb.addEventListener("change", function () {
      if (cb.checked) {
        toolsDraft.push(entry);
      } else {
        toolsDraft.splice(index, 1);
      }
      renderToolsPicker();
    });
    const name = document.createElement("span");
    name.className = "sn-tool-name";
    name.textContent = spec ? spec.label : entry.tool;
    label.appendChild(cb);
    label.appendChild(name);
    head.appendChild(label);

    if (spec && spec.deterministic) {
      const chip = document.createElement("span");
      chip.className = "sn-tool-chip";
      chip.textContent = "no AI cost";
      head.appendChild(chip);
    }

    if (index >= 0) {
      const order = document.createElement("span");
      order.className = "sn-tool-order";
      order.textContent = String(index + 1);
      head.appendChild(order);
      head.appendChild(
        moveButton("▲", "Run earlier", index > 0, function () {
          moveTool(index, -1);
        })
      );
      head.appendChild(
        moveButton("▼", "Run later", index < toolsDraft.length - 1, function () {
          moveTool(index, 1);
        })
      );
    }
    row.appendChild(head);

    const desc = document.createElement("div");
    desc.className = "sn-tool-desc";
    desc.textContent = spec ? spec.description : "";
    if (desc.textContent) {
      row.appendChild(desc);
    }
    if (reason) {
      const why = document.createElement("div");
      why.className = "sn-tool-why";
      why.textContent = reason;
      row.appendChild(why);
    }
    if (index >= 0 && spec && spec.params_schema) {
      row.appendChild(toolParamsForm(entry, spec.params_schema));
    }
    return row;
  }

  /**
   * Build one ▲/▼ order button.
   * @param {string} glyph The arrow.
   * @param {string} title The tooltip.
   * @param {boolean} enabled Whether the move is possible.
   * @param {function()} onClick The move.
   * @return {!HTMLButtonElement}
   */
  function moveButton(glyph, title, enabled, onClick) {
    const btn = document.createElement("button");
    btn.type = "button";
    btn.className = "sn-iconbtn sn-tool-move";
    btn.textContent = glyph;
    btn.title = title;
    btn.disabled = !enabled;
    btn.addEventListener("click", onClick);
    return btn;
  }

  /**
   * Swap a chain entry with its neighbour and re-render.
   * @param {number} index The entry's position.
   * @param {number} delta -1 to move it earlier, +1 later.
   */
  function moveTool(index, delta) {
    const target = index + delta;
    if (target < 0 || target >= toolsDraft.length) {
      return;
    }
    const moved = toolsDraft[index];
    toolsDraft[index] = toolsDraft[target];
    toolsDraft[target] = moved;
    renderToolsPicker();
  }

  /**
   * Build a tool's params mini-form from its pydantic JSON schema. Only the properties this
   * build knows are rendered; anything else already in `entry.params` is left untouched (it may
   * belong to a newer release, and dropping it here would delete it on the next save).
   * @param {!Object} entry The chain entry whose params are edited in place.
   * @param {!Object} schema The tool's params_schema.
   * @return {!HTMLElement}
   */
  function toolParamsForm(entry, schema) {
    const wrap = document.createElement("div");
    wrap.className = "sn-tool-params";
    const props = (schema && schema.properties) || {};
    Object.keys(props).forEach(function (key) {
      wrap.appendChild(toolParamControl(entry, key, props[key] || {}));
    });
    return wrap;
  }

  /**
   * Build one param control, picked from the property's JSON-schema shape: a checkbox for a
   * boolean, a dropdown for an enum, a field picker for a `*_field` name, else a text box.
   * @param {!Object} entry The chain entry being edited.
   * @param {string} key The param name.
   * @param {!Object} prop Its JSON-schema property.
   * @return {!HTMLElement}
   */
  function toolParamControl(entry, key, prop) {
    const current = entry.params[key] !== undefined ? entry.params[key] : prop.default;
    const row = document.createElement("label");
    row.className = "sn-tool-param";
    row.title = prop.description || "";
    const text = document.createElement("span");
    text.className = "sn-tool-param-label";
    text.textContent = prop.title || key;

    let input;
    if (prop.type === "boolean") {
      input = makeCheckbox("sn-tool-param-input", !!current);
      input.addEventListener("change", function () {
        entry.params[key] = input.checked;
      });
    } else if (Array.isArray(prop.enum) || /_field$/.test(key)) {
      const values = Array.isArray(prop.enum) ? prop.enum : [""].concat(fieldNames());
      input = document.createElement("select");
      input.className = "sn-tool-param-input";
      let matched = false;
      values.forEach(function (value) {
        const shown = value === "" ? "(default)" : value;
        input.appendChild(opt(value, shown, value === current));
        matched = matched || value === current;
      });
      if (!matched && current) {
        // A value this build can't offer (a field that was renamed, an option from a newer
        // release) is kept selectable so Done can't silently rewrite it.
        input.appendChild(opt(String(current), String(current) + " (saved)", true));
      }
      input.addEventListener("change", function () {
        entry.params[key] = input.value;
      });
    } else {
      input = document.createElement("input");
      input.type = prop.type === "integer" || prop.type === "number" ? "number" : "text";
      input.className = "sn-tool-param-input";
      input.value = current === undefined || current === null ? "" : String(current);
      input.addEventListener("input", function () {
        entry.params[key] =
          input.type === "number" ? Number(input.value) : input.value;
      });
    }
    row.appendChild(text);
    row.appendChild(input);
    return row;
  }

  /** Every field name on this note type (base first), for the `*_field` param pickers. */
  function fieldNames() {
    const names = [baseSel.value];
    Array.prototype.forEach.call(tbody.querySelectorAll("tr"), function (tr) {
      names.push(tr.dataset.field);
    });
    return names.filter(Boolean);
  }

  toolsClose.addEventListener("click", closeToolsPicker);
  toolsCancel.addEventListener("click", closeToolsPicker);
  toolsModal.addEventListener("click", function (e) {
    if (e.target === toolsModal) {
      closeToolsPicker();
    }
  });
  toolsDone.addEventListener("click", function () {
    if (toolsRow) {
      writeTools(toolsRow, toolsDraft);
    }
    closeToolsPicker();
  });
