
  /**
   * Smart Notes config page — the per-row Tools picker (a MIDDLE fragment of the page IIFE; it
   * neither opens nor closes it). A field is generated by an ORDERED CHAIN of tools, tried
   * top-down until one produces a result, so a free deterministic tool (cloze) can run first and
   * only fall through to the paid `ai` tool when it declines. An EMPTY chain is the legacy
   * default and means exactly "generate with AI".
   *
   * The chain lives as JSON on the row's data-tools attribute — the same single-source-of-truth
   * trick as data-depends-on — so `collectRows` (03-render.js) posts it with every other row
   * value and the existing Save persists it. The catalog of installable tools is BAKED into
   * `window.__SN_TOOLS` server-side (like `__SN_CATALOG`), so the picker paints on first open
   * with no pycmd round-trip.
   *
   * `makeToolsCell` / `updateToolsSummary` / `readTools` / `writeTools` are hoisted function
   * declarations called from 03-render.js, which is concatenated BEFORE this file.
   */

  // [{name, label, description, kinds, deterministic, required_params, params_schema,
  //   unavailable_reason}, ...]
  // `unavailable_reason` is ADVICE ("MP3 voices need the audio runtime"), not a gate — see
  // toolAdvice; `required_params` IS a gate, and the only one here — see missingRequired.
  const TOOLS = window.__SN_TOOLS || [];

  const toolsModal = document.getElementById("sn-tools-modal");
  const toolsTitle = document.getElementById("sn-tools-title");
  const toolsList = document.getElementById("sn-tools-list");
  const toolsEmpty = document.getElementById("sn-tools-empty");
  const toolsWarn = document.getElementById("sn-tools-warn");
  const toolsClose = document.getElementById("sn-tools-close");
  const toolsCancel = document.getElementById("sn-tools-cancel");
  const toolsDone = document.getElementById("sn-tools-done");

  // The row whose chain is open in the picker (null when closed) + the working copy being
  // edited. Cancel simply drops the copy, so the row is only ever touched by Done.
  let toolsRow = null;
  let toolsDraft = [];
  // Set by a Done that was refused, so the required-param errors only appear once the user has
  // actually tried to finish. Cleared on every open — a fresh picker starts quiet.
  let toolsShowErrors = false;

  /**
   * The catalog entry for a tool name, or null when this build doesn't have it (a user tool
   * authored on another device — its name is still kept in the chain).
   * @param {string} name The tool name.
   * @return {?Object}
   */
  function toolSpec(name) {
    let found = null;
    TOOLS.forEach(function (spec) {
      if (spec.name === name) {
        found = spec;
      }
    });
    return found;
  }

  /**
   * Read a row's tool chain (JSON on its data-tools attribute).
   * @param {!HTMLElement} tr The row.
   * @return {!Array<!Object>} The chain entries ({tool, params}); [] if unset/invalid.
   */
  function readTools(tr) {
    try {
      const parsed = JSON.parse(tr.dataset.tools || "[]");
      return Array.isArray(parsed) ? parsed : [];
    } catch (e) {
      return [];
    }
  }

  /**
   * Write a row's tool chain back and refresh its summary button.
   * @param {!HTMLElement} tr The row.
   * @param {!Array<!Object>} chain The ordered entries ({tool, params}).
   */
  function writeTools(tr, chain) {
    tr.dataset.tools = JSON.stringify(chain || []);
    updateToolsSummary(tr);
    // Editing the chain is exactly what changes whether the row reaches a provider, and it was
    // the one event that never re-ran the check — so a row set to `cloze` alone kept its faded
    // Provider/Model after `ai` was appended, and `.sn-na` is `pointer-events: none`, making
    // those cells unclickable for a chain that would use them until the table was rebuilt.
    const typeSel = tr.querySelector(".sn-type");
    applyKindState(tr, (typeSel && typeSel.value) || "text");
  }

  /**
   * Build the Tools cell: a button whose label IS the chain ("cloze → AI"), opening the picker.
   * @param {!HTMLTableRowElement} tr The owning row.
   * @return {!HTMLTableCellElement}
   */
  function makeToolsCell(tr) {
    // NOT `sn-lockable`: that class carries `pointer-events: none` + a blur, which is what
    // actually froze this cell. The lock means "auto-smart must not overwrite my prompt" and
    // that generator writes only `type` and `prompt` — the tool chain is the user's own knob.
    const td = cell("sn-tools-cell");
    const btn = document.createElement("button");
    btn.type = "button";
    btn.className = "sn-btn sn-tools-btn";
    btn.addEventListener("click", function () {
      openToolsPicker(tr);
    });
    td.appendChild(btn);
    return td;
  }

  /**
   * Reflect the row's chain on its Tools button ("AI" when empty — that IS the default).
   * @param {!HTMLTableRowElement} tr The row to refresh.
   */
  function updateToolsSummary(tr) {
    const btn = tr.querySelector(".sn-tools-btn");
    if (!btn) {
      return;
    }
    const chain = readTools(tr);
    const labels = chain.map(function (entry) {
      const spec = toolSpec(entry.tool);
      return spec ? spec.label : entry.tool;
    });
    // One chip per tool rather than one run-on string: the chain IS a sequence, and a row of
    // labelled chips shows its shape — and each tool's own colour — at a glance. An empty chain
    // still reads "AI", because that is exactly what it compiles to.
    btn.textContent = "";
    const shown = chain.length ? chain : [{tool: "ai"}];
    shown.forEach(function (entry, index) {
      if (index) {
        const arrow = document.createElement("span");
        arrow.className = "sn-chip-arrow";
        arrow.textContent = "→";
        btn.appendChild(arrow);
      }
      const spec = toolSpec(entry.tool);
      const chip = document.createElement("span");
      // A per-tool class so each gets its own look; a user tool this build does not know falls
      // back to the base chip rather than rendering unstyled.
      chip.className =
        "sn-chip sn-chip-" + String(entry.tool).replace(/[^a-z0-9]+/gi, "-");
      chip.textContent = spec ? spec.label : entry.tool;
      btn.appendChild(chip);
    });
    btn.classList.toggle("sn-tools-default", !chain.length);
    btn.title = labels.length
      ? "Tried in order until one produces: " + labels.join(" → ")
      : "Generated by AI (the default) — click to add a deterministic tool first.";
  }

  /**
   * Open the picker for a row, on a COPY of its chain (Cancel must change nothing).
   * @param {!HTMLTableRowElement} tr The row whose chain is edited.
   */
  function openToolsPicker(tr) {
    toolsRow = tr;
    toolsShowErrors = false;
    toolsDraft = readTools(tr)
      .filter(function (entry) {
        return entry && entry.tool;
      })
      .map(function (entry) {
        // Copy the params object rather than reference it: a param this build cannot render
        // (added by a newer release) must survive Done untouched.
        const params = {};
        Object.keys(entry.params || {}).forEach(function (key) {
          params[key] = entry.params[key];
        });
        return {tool: String(entry.tool), params: params};
      });
    toolsTitle.textContent = "Tools — " + tr.dataset.field;
    renderToolsPicker();
    toolsModal.hidden = false;
  }

  /** Close the picker without touching the row. */
  function closeToolsPicker() {
    toolsModal.hidden = true;
    toolsRow = null;
    toolsDraft = [];
  }

  /** The generation kind of the row being edited ("" when the picker is closed). */
  function toolsRowKind() {
    if (!toolsRow) {
      return "";
    }
    const sel = toolsRow.querySelector(".sn-type");
    return sel ? sel.value : "";
  }

  /**
   * Why a tool CANNOT go in this row's chain, or "" when it can. Only structural reasons gate:
   * this build doesn't have the tool, or the tool can't serve the row's type.
   * @param {?Object} spec The catalog entry (null = not installed here).
   * @param {string} kind The row's generation kind.
   * @return {string}
   */
  function toolBlocked(spec, kind) {
    if (!spec) {
      return "Not installed on this device — this field skips it and tries the next tool.";
    }
    if ((spec.kinds || []).indexOf(kind) < 0) {
      return "Can't generate a “" + (TYPE_LABELS[kind] || kind) + "” field.";
    }
    return "";
  }

  /**
   * What the tool reports this machine is missing, or "" — ADVICE, which never disables it.
   * A tool answers `availability` for the whole build, but what it needs can depend on the row
   * (a runtime only some voices need, and the voice is a per-row setting), so gating on it
   * would lock a user out of a tool that works perfectly for them.
   * @param {?Object} spec The catalog entry.
   * @return {string}
   */
  function toolAdvice(spec) {
    return (spec && spec.unavailable_reason) || "";
  }

  /**
   * The param names a tool insists on, as a lookup. Server-side truth (`required_params` in
   * the catalog), so a user-authored tool declares its own and this needs no changes.
   * @param {?Object} spec The catalog entry, or null for a tool this build lacks.
   * @return {!Object<string, boolean>}
   */
  function requiredParams(spec) {
    const required = {};
    ((spec && spec.required_params) || []).forEach(function (key) {
      required[key] = true;
    });
    return required;
  }

  /**
   * Whether a param's current value counts as filled in.
   * @param {!Object} entry The chain entry.
   * @param {string} key The param name.
   * @return {boolean}
   */
  function paramFilled(entry, key) {
    const value = entry.params[key];
    return value !== undefined && value !== null && String(value).trim() !== "";
  }

  /**
   * The draft's unfilled required params, one entry per offending tool.
   *
   * A tool whose blank param silently resolves to a fallback ("the field's first prompt
   * reference, else the base field") is unreadable in a picker: the box shows "(default)" and
   * the user cannot tell WHICH field will be read — which, for the tools that derive their
   * output from other fields, is exactly the choice that decides what gets generated. So a
   * tool names those params server-side and Done refuses while any is blank, naming both.
   *
   * A tool this build doesn't have is skipped: its params can't be judged without its schema,
   * and a chain authored on another device must stay editable here.
   * @return {!Array<{tool: string, params: !Array<string>}>}
   */
  function missingRequired() {
    const problems = [];
    const kind = toolsRowKind();
    toolsDraft.forEach(function (entry) {
      const spec = toolSpec(entry.tool);
      // Skip a tool this build lacks (no schema to judge it by) and one that cannot serve this
      // row's kind — the pipeline discards the latter as `wrong_kind`, so refusing Done over
      // its params gates on a tool that will never run. Reachable from a chain synced from a
      // device whose row had a different Type.
      if (!spec || (spec.kinds || []).indexOf(kind) < 0) {
        return;
      }
      const props = (spec.params_schema && spec.params_schema.properties) || {};
      const missing = [];
      Object.keys(requiredParams(spec)).forEach(function (key) {
        if (!paramFilled(entry, key)) {
          missing.push((props[key] && props[key].title) || key);
        }
      });
      if (missing.length) {
        problems.push({tool: spec.label, params: missing});
      }
    });
    return problems;
  }

  /**
   * The one-line message for a set of unfilled required params.
   * @param {!Array<{tool: string, params: !Array<string>}>} problems From missingRequired.
   * @return {string} Empty when there is nothing to say.
   */
  function missingRequiredMessage(problems) {
    if (!problems.length) {
      return "";
    }
    const parts = problems.map(function (problem) {
      return "“" + problem.tool + "” needs " + problem.params.join(" and ");
    });
    const one =
      problems.length === 1 && problems[0].params.length === 1
        ? " Pick a field — left unset the tool guesses one, and you cannot see which."
        : " Pick a field for each — left unset the tool guesses one, and you cannot see which.";
    return parts.join("; ") + "." + one;
  }

  /** Render the whole picker: the chain in order, then the tools that could still be added. */
  function renderToolsPicker() {
    const kind = toolsRowKind();
    toolsList.innerHTML = "";
    const inChain = {};
    toolsDraft.forEach(function (entry, index) {
      inChain[entry.tool] = true;
      toolsList.appendChild(toolEntryRow(entry, index, kind));
    });
    let offered = 0;
    TOOLS.forEach(function (spec) {
      if (inChain[spec.name] || (spec.kinds || []).indexOf(kind) < 0) {
        return;
      }
      offered += 1;
      toolsList.appendChild(toolEntryRow({tool: spec.name, params: {}}, -1, kind));
    });
    toolsEmpty.textContent =
      toolsDraft.length || offered
        ? ""
        : "No tool can generate this field type — it is generated by AI.";
    // Only AFTER a rejected Done: flagging every blank the moment a tool is ticked would shout
    // at the user before they have had a chance to fill anything in. Once it has fired it stays
    // live, so the message clears itself as the fields are picked.
    const message = toolsShowErrors ? missingRequiredMessage(missingRequired()) : "";
    toolsWarn.textContent = message;
    toolsWarn.hidden = !message;
  }

  /**
   * Build one tool's row: include checkbox, order controls, description, and its params form.
   * @param {!Object} entry The chain entry ({tool, params}).
   * @param {number} index Its position in the chain, or -1 when it isn't in it.
   * @param {string} kind The row's generation kind.
   * @return {!HTMLElement}
   */
  function toolEntryRow(entry, index, kind) {
    const spec = toolSpec(entry.tool);
    const blocked = toolBlocked(spec, kind);
    const row = document.createElement("div");
    row.className = "sn-tool-row" + (blocked ? " sn-tool-unavailable" : "");

    const head = document.createElement("div");
    head.className = "sn-tool-head";

    const label = document.createElement("label");
    label.className = "sn-tool-label";
    const cb = makeCheckbox("sn-tool-include", index >= 0);
    // An unusable tool can't be ADDED, but one already configured stays removable — otherwise a
    // chain that became invalid (type changed on another device) could never be repaired here.
    cb.disabled = !!blocked && index < 0;
    cb.addEventListener("change", function () {
      if (cb.checked) {
        toolsDraft.push(entry);
      } else {
        toolsDraft.splice(index, 1);
      }
      renderToolsPicker();
    });
    const name = document.createElement("span");
    name.className = "sn-tool-name";
    name.textContent = spec ? spec.label : entry.tool;
    label.appendChild(cb);
    label.appendChild(name);
    head.appendChild(label);

    if (spec && spec.deterministic) {
      const chip = document.createElement("span");
      chip.className = "sn-tool-chip";
      chip.textContent = "no AI cost";
      head.appendChild(chip);
    }

    if (index >= 0) {
      const order = document.createElement("span");
      order.className = "sn-tool-order";
      order.textContent = String(index + 1);
      head.appendChild(order);
      head.appendChild(
        moveButton("▲", "Run earlier", index > 0, function () {
          moveTool(index, -1);
        })
      );
      head.appendChild(
        moveButton("▼", "Run later", index < toolsDraft.length - 1, function () {
          moveTool(index, 1);
        })
      );
    }
    row.appendChild(head);

    const desc = document.createElement("div");
    desc.className = "sn-tool-desc";
    desc.textContent = spec ? spec.description : "";
    if (desc.textContent) {
      row.appendChild(desc);
    }
    if (blocked) {
      const why = document.createElement("div");
      why.className = "sn-tool-why";
      why.textContent = blocked;
      row.appendChild(why);
    }
    const advice = toolAdvice(spec);
    if (advice) {
      const note = document.createElement("div");
      note.className = "sn-tool-note";
      note.textContent = advice;
      row.appendChild(note);
    }
    if (index >= 0 && spec && spec.params_schema) {
      row.appendChild(toolParamsForm(entry, spec.params_schema, requiredParams(spec)));
    }
    return row;
  }

  /**
   * Build one ▲/▼ order button.
   * @param {string} glyph The arrow.
   * @param {string} title The tooltip.
   * @param {boolean} enabled Whether the move is possible.
   * @param {function()} onClick The move.
   * @return {!HTMLButtonElement}
   */
  function moveButton(glyph, title, enabled, onClick) {
    const btn = document.createElement("button");
    btn.type = "button";
    btn.className = "sn-iconbtn sn-tool-move";
    btn.textContent = glyph;
    btn.title = title;
    btn.disabled = !enabled;
    btn.addEventListener("click", onClick);
    return btn;
  }

  /**
   * Swap a chain entry with its neighbour and re-render.
   * @param {number} index The entry's position.
   * @param {number} delta -1 to move it earlier, +1 later.
   */
  function moveTool(index, delta) {
    const target = index + delta;
    if (target < 0 || target >= toolsDraft.length) {
      return;
    }
    const moved = toolsDraft[index];
    toolsDraft[index] = toolsDraft[target];
    toolsDraft[target] = moved;
    renderToolsPicker();
  }

  /**
   * Build a tool's params mini-form from its pydantic JSON schema. Only the properties this
   * build knows are rendered; anything else already in `entry.params` is left untouched (it may
   * belong to a newer release, and dropping it here would delete it on the next save).
   * @param {!Object} entry The chain entry whose params are edited in place.
   * @param {!Object} schema The tool's params_schema.
   * @param {!Object<string, boolean>} required The params this tool will not accept blank.
   * @return {!HTMLElement}
   */
  function toolParamsForm(entry, schema, required) {
    const wrap = document.createElement("div");
    wrap.className = "sn-tool-params";
    const props = (schema && schema.properties) || {};
    Object.keys(props).forEach(function (key) {
      wrap.appendChild(toolParamControl(entry, key, props[key] || {}, !!required[key]));
    });
    return wrap;
  }

  /**
   * Build one param control, picked from the property's JSON-schema shape: a checkbox for a
   * boolean, a dropdown for an enum, a field picker for a `*_field` name, else a text box.
   * @param {!Object} entry The chain entry being edited.
   * @param {string} key The param name.
   * @param {!Object} prop Its JSON-schema property.
   * @param {boolean} required Whether the tool refuses this param blank.
   * @return {!HTMLElement}
   */
  function toolParamControl(entry, key, prop, required) {
    const current = entry.params[key] !== undefined ? entry.params[key] : prop.default;
    const row = document.createElement("label");
    row.className = "sn-tool-param";
    if (required && toolsShowErrors && !paramFilled(entry, key)) {
      row.className += " sn-tool-param-missing";
    }
    row.title = prop.description || "";
    const text = document.createElement("span");
    text.className = "sn-tool-param-label";
    text.textContent = (prop.title || key) + (required ? " *" : "");

    let input;
    if (prop.type === "boolean") {
      input = makeCheckbox("sn-tool-param-input", !!current);
      input.addEventListener("change", function () {
        entry.params[key] = input.checked;
      });
    } else if (Array.isArray(prop.enum) || /_field$/.test(key)) {
      // A required field param offers no blank CHOICE: "(default)" is precisely the state Done
      // rejects, so leaving it selectable is a trap rather than an option.
      const values = Array.isArray(prop.enum)
        ? prop.enum
        : (required ? [] : [""]).concat(fieldNames());
      input = document.createElement("select");
      input.className = "sn-tool-param-input";
      let matched = false;
      if (required && !paramFilled(entry, key)) {
        // …but it still needs a placeholder, because a <select> whose options are all real
        // fields SHOWS the first one as selected while the param is in fact unset — the box
        // would read "Word" while Done insists the field is missing. This says "unset" out
        // loud, and being disabled it cannot be chosen back.
        const placeholder = opt("", "— pick a field —", true);
        placeholder.disabled = true;
        input.appendChild(placeholder);
      }
      values.forEach(function (value) {
        const shown = value === "" ? "(default)" : value;
        input.appendChild(opt(value, shown, value === current));
        matched = matched || value === current;
      });
      if (!matched && current) {
        // A value this build can't offer (a field that was renamed, an option from a newer
        // release) is kept selectable so Done can't silently rewrite it.
        input.appendChild(opt(String(current), String(current) + " (saved)", true));
      }
      input.addEventListener("change", function () {
        entry.params[key] = input.value;
        if (required && toolsShowErrors) {
          // Re-render so the banner and the red labels track what is still missing. Without
          // this the comment above was a promise nothing kept: filling Source Field left both
          // labels red and the message naming both params until Done was pressed again.
          renderToolsPicker();
        }
      });
    } else {
      input = document.createElement("input");
      input.type = prop.type === "integer" || prop.type === "number" ? "number" : "text";
      input.className = "sn-tool-param-input";
      input.value = current === undefined || current === null ? "" : String(current);
      input.addEventListener("input", function () {
        entry.params[key] =
          input.type === "number" ? Number(input.value) : input.value;
      });
    }
    row.appendChild(text);
    row.appendChild(input);
    return row;
  }

  /**
   * Every field a tool on the OPEN row may read (base first), for the `*_field` param pickers.
   *
   * The row's own field is left out: a tool reading the field it generates is a self-edge in
   * the dependency graph, and it cannot ever be what the user meant — `cloze` would be asked to
   * find its word in the very field it is about to overwrite. Harmless while these params were
   * optional and rarely set; one click away now that they are required and the dropdown holds
   * nothing but real field names.
   */
  function fieldNames() {
    const own = ((toolsRow && toolsRow.dataset.field) || "").toLowerCase();
    const names = [baseSel.value];
    Array.prototype.forEach.call(tbody.querySelectorAll("tr"), function (tr) {
      names.push(tr.dataset.field);
    });
    return names.filter(function (name) {
      return name && name.toLowerCase() !== own;
    });
  }

  toolsClose.addEventListener("click", closeToolsPicker);
  toolsCancel.addEventListener("click", closeToolsPicker);
  toolsModal.addEventListener("click", function (e) {
    if (e.target === toolsModal) {
      closeToolsPicker();
    }
  });
  toolsDone.addEventListener("click", function () {
    // Done is the gate: a chain missing a required param is neither written nor closed away,
    // because a picker that accepts it hands the user a row that silently generates from a
    // field they never chose. Cancel still closes — it discards the draft either way.
    toolsShowErrors = true;
    if (missingRequired().length) {
      renderToolsPicker();
      return;
    }
    if (toolsRow) {
      writeTools(toolsRow, toolsDraft);
    }
    closeToolsPicker();
  });
